 #pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int n=0;
int tt;
long s1max=0,  s1min=10000,
s2max=0,  s2min=10000,
s3max=0,  s3min=10000,
s4max=0,  s4min=10000;



void kalibr()
{
	nMotorEncoder[left]=0;
	nMotorEncoder[right]=0;

	while((nMotorEncoder[left]<600) &&( nMotorEncoder[right]<600))
	{
		motor[right]=10;
		motor[left]=-10;

		int s1m=SensorRaw[S1];
		if (s1m<s1min) s1min=s1m;
		if (s1m>s1max) s1max=s1m;
		int s2m=SensorRaw[S2];
		if (s2m<s2min) s2min=s2m;
		if (s2m>s2max) s2max=s2m;
		int s3m=SensorRaw[S3];
		if (s3m<s3min) s3min=s3m;
		if (s3m>s3max) s3max=s3m;
		int s4m=SensorRaw[S4];
		if (s4m<s4min) s4min=s4m;
		if (s4m>s4max) s4max=s4m;

		n++;


	}


}
task main()
{
	clearTimer(T1);
  int df=fileOpenWrite("rdat");

	kalibr();

fileWriteLong(df,s1min);
fileWriteLong(df,s1max);

fileWriteLong(df,s2min);
fileWriteLong(df,s2max);

fileWriteLong(df,s3min);
fileWriteLong(df,s3max);

fileWriteLong(df,s4min);
fileWriteLong(df,s4max);



fileClose(df);

	tt=time1[T1];

}
