#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int n=0;
int tt;

int df=fileOpenRead("rdat");

long s1max,  s1min,
s2max,  s2min,
s3max,  s3min,
s4max,  s4min;

task main()
{
	clearTimer(T1);

fileReadLong(df,&s1min);
fileReadLong(df,&s1max);

fileReadLong(df,&s2min);
fileReadLong(df,&s2max);


fileReadLong(df,&s3min);
fileReadLong(df,&s3max);

fileReadLong(df,&s4min);
fileReadLong(df,&s4max);

fileClose(df);

	int w0=0;
	float kp=0.065;
	float kd=0.5;
	int v=29;

	while (true)
	{
		n++;
		int i1=abs((SensorRaw[S1]-s1min))*100/(s1max-s1min);
		int i2=abs((SensorRaw[S2]-s2min))*100/(s2max-s2min);
		int i3=abs((SensorRaw[S3]-s3min))*100/(s3max-s3min);
		int i4=abs((SensorRaw[S4]-s4min))*100/(s4max-s4min);

		int w=1.2*i1+i2-i3-1.2*i4;
		//	int er2=i1-i4;
		int sw=w-w0;  //speed
		float er2=sw*kd;
		float er1=w*kp;

		float er=er1+er2;
		motor[left]=v-er;
		motor[right]=v+er;

	  w0=w;

		tt=time1[T1];
		}
}
